baseURL = "/"
languageCode = "en-us"
title = "LDAP Proxy"

[blackfriday]
  angledQuotes = true
  fractions = false
  plainIDAnchors = true
  smartlists = true
  extensions = ["hardLineBreak"]

[params]
  author = "Thomas Boerger"
  description = "Proxy for authentication via LDAP"
  keywords = "proxy, ldap, authentication"
